; generated by PrusaSlicer 2.6.0+win64 on 2023-07-28 at 07:41:16 UTC

; 

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.40mm

M201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1500 R1500 T1500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X10.00 Y10.00 Z0.20 E2.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M190 S60 ; set bed temperature and wait for it to be reached
M104 S215 ; set temperature
;TYPE:Custom
M900 K0.13 ;lin_adv fact
G28 ;Home
G29 ;auto level

G1 Z15.0 F6000 ;Move the platform down 15mm
G92 E0
G1 F200 E5
G92 E0
M109 S215 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M900 K0.06 ;lin_adv fact
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z.2 F1800
G10 ; retract
G92 E0
G1 X0 Y-21.785
G11 ; unretract
G92 E0
M204 P500
;TYPE:Skirt/Brim
;WIDTH:0.4
G1 F2400
G1 X50 Y-21.785 E1.48456
G1 X52.287 Y-21.388 E1.55348
G1 X54.306 Y-20.244 E1.62238
G1 X55.822 Y-18.485 E1.69133
G1 X56.656 Y-16.319 E1.76024
G1 X56.785 Y-15 E1.79959
G1 X56.785 Y15 E2.69033
G1 X56.388 Y17.287 E2.75925
G1 X55.244 Y19.306 E2.82815
G1 X53.485 Y20.822 E2.8971
G1 X51.319 Y21.656 E2.96601
G1 X50 Y21.785 E3.00536
G1 X-50 Y21.785 E5.97449
G1 X-52.287 Y21.388 E6.04341
G1 X-54.306 Y20.244 E6.11231
G1 X-55.822 Y18.485 E6.18126
G1 X-56.656 Y16.319 E6.25017
G1 X-56.785 Y15 E6.28952
G1 X-56.785 Y-15 E7.18026
G1 X-56.388 Y-17.287 E7.24918
G1 X-55.244 Y-19.306 E7.31808
G1 X-53.485 Y-20.822 E7.38703
G1 X-51.319 Y-21.656 E7.45594
G1 X-50 Y-21.785 E7.49529
G1 X-.06 Y-21.785 E8.97807
G10 ; retract
G92 E0
G1 X-.06 Y-21.428 F1800
G11 ; unretract
G92 E0
G1 F2400
G1 X50 Y-21.428 E1.48635
G1 X52.224 Y-21.031 E1.55343
G1 X54.173 Y-19.89 E1.62049
G1 X55.607 Y-18.144 E1.68757
G1 X56.428 Y-15 E1.78405
G1 X56.428 Y15 E2.67479
G1 X56.031 Y17.224 E2.74187
G1 X54.89 Y19.173 E2.80893
G1 X53.144 Y20.607 E2.87601
G1 X50 Y21.428 E2.97249
G1 X-50 Y21.428 E5.94162
G1 X-52.224 Y21.031 E6.0087
G1 X-54.173 Y19.89 E6.07576
G1 X-55.607 Y18.144 E6.14284
G1 X-56.428 Y15 E6.23932
G1 X-56.428 Y-15 E7.13006
G1 X-56.031 Y-17.224 E7.19714
G1 X-54.89 Y-19.173 E7.2642
G1 X-53.144 Y-20.607 E7.33128
G1 X-50 Y-21.428 E7.42776
G1 X-.12 Y-21.428 E8.90876
G10 ; retract
G92 E0
G1 X-.12 Y-21.071 F1800
G11 ; unretract
G92 E0
G1 F2400
G1 X50 Y-21.071 E1.48813
G1 X52.159 Y-20.675 E1.5533
G1 X54.035 Y-19.536 E1.61846
G1 X55.384 Y-17.805 E1.68362
G1 X56.071 Y-15 E1.76937
G1 X56.071 Y15 E2.66011
G1 X55.675 Y17.159 E2.72528
G1 X54.536 Y19.035 E2.79044
G1 X52.805 Y20.384 E2.8556
G1 X50 Y21.071 E2.94135
G1 X-50 Y21.071 E5.91048
G1 X-52.159 Y20.675 E5.97565
G1 X-54.035 Y19.536 E6.04081
G1 X-55.384 Y17.805 E6.10597
G1 X-56.071 Y15 E6.19172
G1 X-56.071 Y-15 E7.08246
G1 X-55.675 Y-17.159 E7.14763
G1 X-54.536 Y-19.035 E7.21279
G1 X-52.805 Y-20.384 E7.27795
G1 X-50 Y-21.071 E7.3637
G1 X-.18 Y-21.071 E8.84292
G10 ; retract
G92 E0
G1 X-.18 Y-20.714 F1800
G11 ; unretract
G92 E0
G1 F2400
G1 X50 Y-20.714 E1.48991
G1 X52.091 Y-20.318 E1.5531
G1 X53.893 Y-19.183 E1.61633
G1 X55.154 Y-17.468 E1.67953
G1 X55.714 Y-15 E1.75467
G1 X55.714 Y15 E2.64541
G1 X55.318 Y17.091 E2.7086
G1 X54.183 Y18.893 E2.77183
G1 X52.468 Y20.154 E2.83503
G1 X50 Y20.714 E2.91017
G1 X-50 Y20.714 E5.8793
G1 X-52.091 Y20.318 E5.94249
G1 X-53.893 Y19.183 E6.00572
G1 X-55.154 Y17.468 E6.06892
G1 X-55.714 Y15 E6.14406
G1 X-55.714 Y-15 E7.0348
G1 X-55.318 Y-17.091 E7.09799
G1 X-54.183 Y-18.893 E7.16122
G1 X-52.468 Y-20.154 E7.22442
G1 X-50 Y-20.714 E7.29956
G1 X-.24 Y-20.714 E8.777
G10 ; retract
G92 E0
G1 X-.24 Y-20.357 F1800
G11 ; unretract
G92 E0
G1 F2400
G1 X50 Y-20.357 E1.49169
G1 X52.022 Y-19.961 E1.55287
G1 X53.745 Y-18.831 E1.61405
G1 X54.914 Y-17.134 E1.67523
G1 X55.357 Y-15 E1.73994
G1 X55.357 Y15 E2.63068
G1 X54.961 Y17.022 E2.69186
G1 X53.831 Y18.745 E2.75304
G1 X52.134 Y19.914 E2.81422
G1 X50 Y20.357 E2.87893
G1 X-50 Y20.357 E5.84806
G1 X-52.022 Y19.961 E5.90924
G1 X-53.745 Y18.831 E5.97042
G1 X-54.914 Y17.134 E6.0316
G1 X-55.357 Y15 E6.09631
G1 X-55.357 Y-15 E6.98705
G1 X-54.961 Y-17.022 E7.04823
G1 X-53.831 Y-18.745 E7.10941
G1 X-52.134 Y-19.914 E7.17059
G1 X-50 Y-20.357 E7.2353
G1 X-.3 Y-20.357 E8.71096
; printing object Shape-Box id:0 copy 0
G10 ; retract
G92 E0
G1 X49.086 Y14.086 F1800
G11 ; unretract
G92 E0
;TYPE:Perimeter
;WIDTH:0.399999
G1 F2400
G1 X-49.086 Y14.086 E2.91485
G1 X-49.086 Y-14.086 E3.75131
G1 X49.086 Y-14.086 E6.66616
G1 X49.086 Y14.026 E7.50084
G10 ; retract
G92 E0
G1 X49.443 Y14.443 F1800
G11 ; unretract
G92 E0
G1 F2400
G1 X-49.443 Y14.443 E2.93605
G1 X-49.443 Y-14.443 E3.79371
G1 X49.443 Y-14.443 E6.72976
G1 X49.443 Y14.383 E7.58564
G10 ; retract
G92 E0
G1 X49.464 Y14.383 F1800
G1 X49.464 Y14.408
G1 X49.8 Y14.8
G11 ; unretract
G92 E0
;TYPE:External perimeter
G1 F2400
G1 X-49.8 Y14.8 E2.95725
G1 X-49.8 Y-14.8 E3.83611
G1 X49.8 Y-14.8 E6.79336
G1 X49.8 Y14.74 E7.67044
G1 X49.402 Y14.762 F1800
G10 ; retract
G92 E0
G1 X49.464 Y8.502
G1 X49.464 Y-14.464
G1 X48.255 Y-14.464
G1 X48.255 Y-13.979
G11 ; unretract
G92 E0
;TYPE:Solid infill
;WIDTH:0.400694
G1 F2400
G1 X48.818 Y-13.416 E.02369
G1 X48.818 Y-12.91 E.03874
G1 X47.91 Y-13.818 E.07694
G1 X47.404 Y-13.818 E.09199
G1 X48.818 Y-12.404 E.15148
G1 X48.818 Y-11.898 E.16653
G1 X46.898 Y-13.818 E.24731
G1 X46.392 Y-13.818 E.26236
G1 X48.818 Y-11.392 E.36443
G1 X48.818 Y-10.886 E.37948
G1 X45.886 Y-13.818 E.50283
G1 X45.38 Y-13.818 E.51788
G1 X48.818 Y-10.38 E.66252
G1 X48.818 Y-9.874 E.67757
G1 X44.874 Y-13.818 E.8435
G1 X44.368 Y-13.818 E.85855
G1 X48.818 Y-9.368 E1.04577
G1 X48.818 Y-8.862 E1.06082
G1 X43.862 Y-13.818 E1.26933
G1 X43.356 Y-13.818 E1.28438
G1 X48.818 Y-8.356 E1.51417
G1 X48.818 Y-7.85 E1.52922
G1 X42.85 Y-13.818 E1.7803
G1 X42.344 Y-13.818 E1.79535
G1 X48.818 Y-7.344 E2.06772
G1 X48.818 Y-6.838 E2.08277
G1 X41.838 Y-13.818 E2.37643
G1 X41.333 Y-13.818 E2.39145
G1 X48.818 Y-6.333 E2.70636
G1 X48.818 Y-5.827 E2.72141
G1 X40.827 Y-13.818 E3.0576
G1 X40.321 Y-13.818 E3.07265
G1 X48.818 Y-5.321 E3.43013
G1 X48.818 Y-4.815 E3.44518
G1 X39.815 Y-13.818 E3.82395
G1 X39.309 Y-13.818 E3.839
G1 X48.818 Y-4.309 E4.23906
G1 X48.818 Y-3.803 E4.25411
G1 X38.803 Y-13.818 E4.67546
G1 X38.297 Y-13.818 E4.69051
G1 X48.818 Y-3.297 E5.13314
G1 X48.818 Y-2.791 E5.14819
G1 X37.791 Y-13.818 E5.61211
G1 X37.285 Y-13.818 E5.62716
G1 X48.818 Y-2.285 E6.11237
G1 X48.818 Y-1.779 E6.12742
G1 X36.779 Y-13.818 E6.63392
G1 X36.273 Y-13.818 E6.64897
G1 X48.818 Y-1.273 E7.17676
G1 X48.818 Y-.767 E7.19181
G1 X35.767 Y-13.818 E7.74088
G1 X35.261 Y-13.818 E7.75593
G1 X48.818 Y-.261 E8.32629
G1 X48.818 Y.245 E8.34134
G1 X34.755 Y-13.818 E8.93299
G1 X34.249 Y-13.818 E8.94804
G1 X48.818 Y.751 E9.56098
G1 X48.818 Y1.257 E9.57603
G1 X33.743 Y-13.818 E10.21026
G1 X33.237 Y-13.818 E10.22531
G1 X48.818 Y1.763 E10.88083
G1 X48.818 Y2.269 E10.89588
G1 X32.731 Y-13.818 E11.57268
G1 X32.225 Y-13.818 E11.58773
G1 X48.818 Y2.775 E12.28582
G1 X48.818 Y3.281 E12.30087
G1 X31.719 Y-13.818 E13.02025
G1 X31.213 Y-13.818 E13.0353
G1 X48.818 Y3.787 E13.77597
G1 X48.818 Y4.293 E13.79102
G1 X30.707 Y-13.818 E14.55298
G1 X30.201 Y-13.818 E14.56803
G1 X48.818 Y4.799 E15.35127
G1 X48.818 Y5.305 E15.36632
G1 X29.695 Y-13.818 E16.17085
G1 X29.189 Y-13.818 E16.1859
G1 X48.818 Y5.811 E17.01172
G1 X48.818 Y6.317 E17.02677
G1 X28.683 Y-13.818 E17.87388
G1 X28.177 Y-13.818 E17.88893
G1 X48.818 Y6.823 E18.75733
G1 X48.818 Y7.329 E18.77238
G1 X27.671 Y-13.818 E19.66207
G1 X27.165 Y-13.818 E19.67712
G1 X48.818 Y7.835 E20.58809
G1 X48.818 Y8.341 E20.60314
G1 X26.659 Y-13.818 E21.5354
G1 X26.153 Y-13.818 E21.55045
G1 X48.818 Y8.847 E22.504
G1 X48.818 Y9.353 E22.51905
G1 X25.647 Y-13.818 E23.49389
G1 X25.142 Y-13.818 E23.50891
G1 X48.818 Y9.858 E24.50499
G1 X48.818 Y10.364 E24.52004
G1 X24.636 Y-13.818 E25.53741
G1 X24.13 Y-13.818 E25.55246
G1 X48.818 Y10.87 E26.59112
G1 X48.818 Y11.376 E26.60617
G1 X23.624 Y-13.818 E27.66612
G1 X23.118 Y-13.818 E27.68117
G1 X48.818 Y11.882 E28.76241
G1 X48.818 Y12.388 E28.77746
G1 X22.612 Y-13.818 E29.87999
G1 X22.106 Y-13.818 E29.89504
G1 X48.818 Y12.894 E31.01885
G1 X48.818 Y13.4 E31.0339
G1 X21.6 Y-13.818 E32.179
G1 X21.094 Y-13.818 E32.19405
G1 X48.73 Y13.818 E33.35674
G1 X48.224 Y13.818 E33.37179
G1 X20.588 Y-13.818 E34.53448
G1 X20.082 Y-13.818 E34.54953
G1 X47.718 Y13.818 E35.71222
G1 X47.212 Y13.818 E35.72727
G1 X19.576 Y-13.818 E36.88996
G1 X19.07 Y-13.818 E36.90501
G1 X46.706 Y13.818 E38.0677
G1 X46.2 Y13.818 E38.08275
G1 X18.564 Y-13.818 E39.24544
G1 X18.058 Y-13.818 E39.26049
G1 X45.694 Y13.818 E40.42318
G1 X45.188 Y13.818 E40.43823
G1 X17.552 Y-13.818 E41.60092
G1 X17.046 Y-13.818 E41.61597
G1 X44.682 Y13.818 E42.77866
G1 X44.176 Y13.818 E42.79371
G1 X16.54 Y-13.818 E43.9564
G1 X16.034 Y-13.818 E43.97145
G1 X43.67 Y13.818 E45.13414
G1 X43.164 Y13.818 E45.14919
G1 X15.528 Y-13.818 E46.31188
G1 X15.022 Y-13.818 E46.32693
G1 X42.658 Y13.818 E47.48962
G1 X42.152 Y13.818 E47.50467
G1 X14.516 Y-13.818 E48.66736
G1 X14.01 Y-13.818 E48.68241
G1 X41.646 Y13.818 E49.8451
G1 X41.14 Y13.818 E49.86015
G1 X13.504 Y-13.818 E51.02284
G1 X12.998 Y-13.818 E51.03789
G1 X40.634 Y13.818 E52.20058
G1 X40.128 Y13.818 E52.21563
G1 X12.492 Y-13.818 E53.37832
G1 X11.986 Y-13.818 E53.39337
G1 X39.622 Y13.818 E54.55606
G1 X39.116 Y13.818 E54.57111
G1 X11.48 Y-13.818 E55.7338
G1 X10.974 Y-13.818 E55.74885
G1 X38.61 Y13.818 E56.91154
G1 X38.104 Y13.818 E56.92659
G1 X10.468 Y-13.818 E58.08928
G1 X9.962 Y-13.818 E58.10433
G1 X37.599 Y13.818 E59.26704
G1 X37.093 Y13.818 E59.28209
G1 X9.456 Y-13.818 E60.4448
G1 X8.951 Y-13.818 E60.45982
G1 X36.587 Y13.818 E61.62251
G1 X36.081 Y13.818 E61.63756
G1 X8.445 Y-13.818 E62.80025
G1 X7.939 Y-13.818 E62.8153
G1 X35.575 Y13.818 E63.97799
G1 X35.069 Y13.818 E63.99304
G1 X7.433 Y-13.818 E65.15573
G1 X6.927 Y-13.818 E65.17078
G1 X34.563 Y13.818 E66.33347
G1 X34.057 Y13.818 E66.34852
G1 X6.421 Y-13.818 E67.51121
G1 X5.915 Y-13.818 E67.52626
G1 X33.551 Y13.818 E68.68895
G1 X33.045 Y13.818 E68.704
G1 X5.409 Y-13.818 E69.86669
G1 X4.903 Y-13.818 E69.88174
G1 X32.539 Y13.818 E71.04443
G1 X32.033 Y13.818 E71.05948
G1 X4.397 Y-13.818 E72.22217
G1 X3.891 Y-13.818 E72.23722
G1 X31.527 Y13.818 E73.39991
G1 X31.021 Y13.818 E73.41496
G1 X3.385 Y-13.818 E74.57765
G1 X2.879 Y-13.818 E74.5927
G1 X30.515 Y13.818 E75.75539
G1 X30.009 Y13.818 E75.77044
G1 X2.373 Y-13.818 E76.93313
G1 X1.867 Y-13.818 E76.94818
G1 X29.503 Y13.818 E78.11087
G1 X28.997 Y13.818 E78.12592
G1 X1.361 Y-13.818 E79.28861
G1 X.855 Y-13.818 E79.30366
G1 X28.491 Y13.818 E80.46635
G1 X27.985 Y13.818 E80.4814
G1 X.349 Y-13.818 E81.64409
G1 X-.157 Y-13.818 E81.65914
G1 X27.479 Y13.818 E82.82183
G1 X26.973 Y13.818 E82.83688
G1 X-.663 Y-13.818 E83.99957
G1 X-1.169 Y-13.818 E84.01462
G1 X26.467 Y13.818 E85.17731
G1 X25.961 Y13.818 E85.19236
G1 X-1.675 Y-13.818 E86.35505
G1 X-2.181 Y-13.818 E86.3701
G1 X25.455 Y13.818 E87.53279
G1 X24.949 Y13.818 E87.54784
G1 X-2.687 Y-13.818 E88.71053
G1 X-3.193 Y-13.818 E88.72558
G1 X24.443 Y13.818 E89.88827
G1 X23.937 Y13.818 E89.90332
G1 X-3.699 Y-13.818 E91.06601
G1 X-4.205 Y-13.818 E91.08106
G1 X23.431 Y13.818 E92.24375
G1 X22.925 Y13.818 E92.2588
G1 X-4.711 Y-13.818 E93.42149
G1 X-5.217 Y-13.818 E93.43654
G1 X22.419 Y13.818 E94.59923
G1 X21.913 Y13.818 E94.61428
G1 X-5.723 Y-13.818 E95.77697
G1 X-6.229 Y-13.818 E95.79202
G1 X21.408 Y13.818 E96.95473
G1 X20.902 Y13.818 E96.96978
G1 X-6.735 Y-13.818 E98.13249
G1 X-7.24 Y-13.818 E98.14751
G1 X20.396 Y13.818 E99.3102
G1 X19.89 Y13.818 E99.32525
G1 X-7.746 Y-13.818 E100.48794
G1 X-8.252 Y-13.818 E100.50299
G1 X19.384 Y13.818 E101.66568
G1 X18.878 Y13.818 E101.68073
G1 X-8.758 Y-13.818 E102.84342
G1 X-9.264 Y-13.818 E102.85847
G1 X18.372 Y13.818 E104.02116
G1 X17.866 Y13.818 E104.03621
G1 X-9.77 Y-13.818 E105.1989
G1 X-10.276 Y-13.818 E105.21395
G1 X17.36 Y13.818 E106.37664
G1 X16.854 Y13.818 E106.39169
G1 X-10.782 Y-13.818 E107.55438
G1 X-11.288 Y-13.818 E107.56943
G1 X16.348 Y13.818 E108.73212
G1 X15.842 Y13.818 E108.74717
G1 X-11.794 Y-13.818 E109.90986
G1 X-12.3 Y-13.818 E109.92491
G1 X15.336 Y13.818 E111.0876
G1 X14.83 Y13.818 E111.10265
G1 X-12.806 Y-13.818 E112.26534
G1 X-13.312 Y-13.818 E112.28039
G1 X14.324 Y13.818 E113.44308
G1 X13.818 Y13.818 E113.45813
G1 X-13.818 Y-13.818 E114.62082
G1 X-14.324 Y-13.818 E114.63587
G1 X13.312 Y13.818 E115.79856
G1 X12.806 Y13.818 E115.81361
G1 X-14.83 Y-13.818 E116.9763
G1 X-15.336 Y-13.818 E116.99135
G1 X12.3 Y13.818 E118.15404
G1 X11.794 Y13.818 E118.16909
G1 X-15.842 Y-13.818 E119.33178
G1 X-16.348 Y-13.818 E119.34683
G1 X11.288 Y13.818 E120.50952
G1 X10.782 Y13.818 E120.52457
G1 X-16.854 Y-13.818 E121.68726
G1 X-17.36 Y-13.818 E121.70231
G1 X10.276 Y13.818 E122.865
G1 X9.77 Y13.818 E122.88005
G1 X-17.866 Y-13.818 E124.04274
G1 X-18.372 Y-13.818 E124.05779
G1 X9.264 Y13.818 E125.22048
G1 X8.758 Y13.818 E125.23553
G1 X-18.878 Y-13.818 E126.39822
G1 X-19.384 Y-13.818 E126.41327
G1 X8.252 Y13.818 E127.57596
G1 X7.746 Y13.818 E127.59101
G1 X-19.89 Y-13.818 E128.7537
G1 X-20.396 Y-13.818 E128.76875
G1 X7.24 Y13.818 E129.93144
G1 X6.734 Y13.818 E129.94649
G1 X-20.902 Y-13.818 E131.10918
G1 X-21.408 Y-13.818 E131.12423
G1 X6.228 Y13.818 E132.28692
G1 X5.722 Y13.818 E132.30197
G1 X-21.914 Y-13.818 E133.46466
G1 X-22.42 Y-13.818 E133.47971
G1 X5.217 Y13.818 E134.64242
G1 X4.711 Y13.818 E134.65747
G1 X-22.926 Y-13.818 E135.82018
G1 X-23.431 Y-13.818 E135.8352
G1 X4.205 Y13.818 E136.99789
G1 X3.699 Y13.818 E137.01294
G1 X-23.937 Y-13.818 E138.17563
G1 X-24.443 Y-13.818 E138.19068
G1 X3.193 Y13.818 E139.35337
G1 X2.687 Y13.818 E139.36842
G1 X-24.949 Y-13.818 E140.53111
G1 X-25.455 Y-13.818 E140.54616
G1 X2.181 Y13.818 E141.70885
G1 X1.675 Y13.818 E141.7239
G1 X-25.961 Y-13.818 E142.88659
G1 X-26.467 Y-13.818 E142.90164
G1 X1.169 Y13.818 E144.06433
G1 X.663 Y13.818 E144.07938
G1 X-26.973 Y-13.818 E145.24207
G1 X-27.479 Y-13.818 E145.25712
G1 X.157 Y13.818 E146.41981
G1 X-.349 Y13.818 E146.43486
G1 X-27.985 Y-13.818 E147.59755
G1 X-28.491 Y-13.818 E147.6126
G1 X-.855 Y13.818 E148.77529
G1 X-1.361 Y13.818 E148.79034
G1 X-28.997 Y-13.818 E149.95303
G1 X-29.503 Y-13.818 E149.96808
G1 X-1.867 Y13.818 E151.13077
G1 X-2.373 Y13.818 E151.14582
G1 X-30.009 Y-13.818 E152.30851
G1 X-30.515 Y-13.818 E152.32356
G1 X-2.879 Y13.818 E153.48625
G1 X-3.385 Y13.818 E153.5013
G1 X-31.021 Y-13.818 E154.66399
G1 X-31.527 Y-13.818 E154.67904
G1 X-3.891 Y13.818 E155.84173
G1 X-4.397 Y13.818 E155.85678
G1 X-32.033 Y-13.818 E157.01947
G1 X-32.539 Y-13.818 E157.03452
G1 X-4.903 Y13.818 E158.19721
G1 X-5.409 Y13.818 E158.21226
G1 X-33.045 Y-13.818 E159.37495
G1 X-33.551 Y-13.818 E159.39
G1 X-5.915 Y13.818 E160.55269
G1 X-6.421 Y13.818 E160.56774
G1 X-34.057 Y-13.818 E161.73043
G1 X-34.563 Y-13.818 E161.74548
G1 X-6.927 Y13.818 E162.90817
G1 X-7.433 Y13.818 E162.92322
G1 X-35.069 Y-13.818 E164.08591
G1 X-35.575 Y-13.818 E164.10096
G1 X-7.939 Y13.818 E165.26365
G1 X-8.445 Y13.818 E165.2787
G1 X-36.081 Y-13.818 E166.44139
G1 X-36.587 Y-13.818 E166.45644
G1 X-8.951 Y13.818 E167.61913
G1 X-9.457 Y13.818 E167.63418
G1 X-37.093 Y-13.818 E168.79687
G1 X-37.599 Y-13.818 E168.81192
G1 X-9.963 Y13.818 E169.97461
G1 X-10.469 Y13.818 E169.98966
G1 X-38.105 Y-13.818 E171.15235
G1 X-38.611 Y-13.818 E171.1674
G1 X-10.974 Y13.818 E172.33011
G1 X-11.48 Y13.818 E172.34516
G1 X-39.117 Y-13.818 E173.50787
G1 X-39.622 Y-13.818 E173.52289
G1 X-11.986 Y13.818 E174.68558
G1 X-12.492 Y13.818 E174.70063
G1 X-40.128 Y-13.818 E175.86332
G1 X-40.634 Y-13.818 E175.87837
G1 X-12.998 Y13.818 E177.04106
G1 X-13.504 Y13.818 E177.05611
G1 X-41.14 Y-13.818 E178.2188
G1 X-41.646 Y-13.818 E178.23385
G1 X-14.01 Y13.818 E179.39654
G1 X-14.516 Y13.818 E179.41159
G1 X-42.152 Y-13.818 E180.57428
G1 X-42.658 Y-13.818 E180.58933
G1 X-15.022 Y13.818 E181.75202
G1 X-15.528 Y13.818 E181.76707
G1 X-43.164 Y-13.818 E182.92976
G1 X-43.67 Y-13.818 E182.94481
G1 X-16.034 Y13.818 E184.1075
G1 X-16.54 Y13.818 E184.12255
G1 X-44.176 Y-13.818 E185.28524
G1 X-44.682 Y-13.818 E185.30029
G1 X-17.046 Y13.818 E186.46298
G1 X-17.552 Y13.818 E186.47803
G1 X-45.188 Y-13.818 E187.64072
G1 X-45.694 Y-13.818 E187.65577
G1 X-18.058 Y13.818 E188.81846
G1 X-18.564 Y13.818 E188.83351
G1 X-46.2 Y-13.818 E189.9962
G1 X-46.706 Y-13.818 E190.01125
G1 X-19.07 Y13.818 E191.17394
G1 X-19.576 Y13.818 E191.18899
G1 X-47.212 Y-13.818 E192.35168
G1 X-47.718 Y-13.818 E192.36673
G1 X-20.082 Y13.818 E193.52942
G1 X-20.588 Y13.818 E193.54447
G1 X-48.224 Y-13.818 E194.70716
G1 X-48.73 Y-13.818 E194.72221
G1 X-21.094 Y13.818 E195.8849
G1 X-21.6 Y13.818 E195.89995
G1 X-48.818 Y-13.4 E197.04505
G1 X-48.818 Y-12.894 E197.0601
G1 X-22.106 Y13.818 E198.18391
G1 X-22.612 Y13.818 E198.19896
G1 X-48.818 Y-12.388 E199.30149
G1 X-48.818 Y-11.882 E199.31654
G1 X-23.118 Y13.818 E200.39778
G1 X-23.624 Y13.818 E200.41283
G1 X-48.818 Y-11.376 E201.47278
G1 X-48.818 Y-10.87 E201.48783
G1 X-24.13 Y13.818 E202.52649
G1 X-24.636 Y13.818 E202.54154
G1 X-48.818 Y-10.364 E203.55891
G1 X-48.818 Y-9.858 E203.57396
G1 X-25.142 Y13.818 E204.57004
G1 X-25.648 Y13.818 E204.58509
G1 X-48.818 Y-9.352 E205.55989
G1 X-48.818 Y-8.846 E205.57494
G1 X-26.154 Y13.818 E206.52845
G1 X-26.66 Y13.818 E206.5435
G1 X-48.818 Y-8.34 E207.47572
G1 X-48.818 Y-7.835 E207.49074
G1 X-27.165 Y13.818 E208.40171
G1 X-27.671 Y13.818 E208.41676
G1 X-48.818 Y-7.329 E209.30645
G1 X-48.818 Y-6.823 E209.3215
G1 X-28.177 Y13.818 E210.1899
G1 X-28.683 Y13.818 E210.20495
G1 X-48.818 Y-6.317 E211.05206
G1 X-48.818 Y-5.811 E211.06711
G1 X-29.189 Y13.818 E211.89293
G1 X-29.695 Y13.818 E211.90798
G1 X-48.818 Y-5.305 E212.71251
G1 X-48.818 Y-4.799 E212.72756
G1 X-30.201 Y13.818 E213.5108
G1 X-30.707 Y13.818 E213.52585
G1 X-48.818 Y-4.293 E214.28781
G1 X-48.818 Y-3.787 E214.30286
G1 X-31.213 Y13.818 E215.04353
G1 X-31.719 Y13.818 E215.05858
G1 X-48.818 Y-3.281 E215.77796
G1 X-48.818 Y-2.775 E215.79301
G1 X-32.225 Y13.818 E216.4911
G1 X-32.731 Y13.818 E216.50615
G1 X-48.818 Y-2.269 E217.18295
G1 X-48.818 Y-1.763 E217.198
G1 X-33.237 Y13.818 E217.85352
G1 X-33.743 Y13.818 E217.86857
G1 X-48.818 Y-1.257 E218.5028
G1 X-48.818 Y-.751 E218.51785
G1 X-34.249 Y13.818 E219.13079
G1 X-34.755 Y13.818 E219.14584
G1 X-48.818 Y-.245 E219.73749
G1 X-48.818 Y.261 E219.75254
G1 X-35.261 Y13.818 E220.3229
G1 X-35.767 Y13.818 E220.33795
G1 X-48.818 Y.767 E220.88702
G1 X-48.818 Y1.273 E220.90207
G1 X-36.273 Y13.818 E221.42986
G1 X-36.779 Y13.818 E221.44491
G1 X-48.818 Y1.779 E221.95141
G1 X-48.818 Y2.285 E221.96646
G1 X-37.285 Y13.818 E222.45167
G1 X-37.791 Y13.818 E222.46672
G1 X-48.818 Y2.791 E222.93064
G1 X-48.818 Y3.297 E222.94569
G1 X-38.297 Y13.818 E223.38832
G1 X-38.803 Y13.818 E223.40337
G1 X-48.818 Y3.803 E223.82472
G1 X-48.818 Y4.309 E223.83977
G1 X-39.309 Y13.818 E224.23983
G1 X-39.815 Y13.818 E224.25488
G1 X-48.818 Y4.815 E224.63365
G1 X-48.818 Y5.321 E224.6487
G1 X-40.321 Y13.818 E225.00618
G1 X-40.827 Y13.818 E225.02123
G1 X-48.818 Y5.827 E225.35742
G1 X-48.818 Y6.333 E225.37247
G1 X-41.333 Y13.818 E225.68738
G1 X-41.839 Y13.818 E225.70243
G1 X-48.818 Y6.839 E225.99605
G1 X-48.818 Y7.345 E226.0111
G1 X-42.345 Y13.818 E226.28343
G1 X-42.851 Y13.818 E226.29848
G1 X-48.818 Y7.851 E226.54952
G1 X-48.818 Y8.356 E226.56454
G1 X-43.356 Y13.818 E226.79433
G1 X-43.862 Y13.818 E226.80938
G1 X-48.818 Y8.862 E227.01789
G1 X-48.818 Y9.368 E227.03294
G1 X-44.368 Y13.818 E227.22016
G1 X-44.874 Y13.818 E227.23521
G1 X-48.818 Y9.874 E227.40114
G1 X-48.818 Y10.38 E227.41619
G1 X-45.38 Y13.818 E227.56083
G1 X-45.886 Y13.818 E227.57588
G1 X-48.818 Y10.886 E227.69923
G1 X-48.818 Y11.392 E227.71428
G1 X-46.392 Y13.818 E227.81635
G1 X-46.898 Y13.818 E227.8314
G1 X-48.818 Y11.898 E227.91218
G1 X-48.818 Y12.404 E227.92723
G1 X-47.404 Y13.818 E227.98672
G1 X-47.91 Y13.818 E228.00177
G1 X-48.818 Y12.91 E228.03997
G1 X-48.818 Y13.416 E228.05502
G1 X-48.255 Y13.979 E228.07871
; stop printing object Shape-Box id:0 copy 0
G10 ; retract
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G91
G1 F1800 E-3
G1 F3000 Z10
G90
M106 S0 ; turn off cooling fan
M104 S0 ; turn off extruder
M140 S0 ; turn off bed
M84 ; disable motors
; filament used [mm] = 300.05
; filament used [cm3] = 0.72
; filament used [g] = 0.90
; filament cost = 0.02
; total filament used [g] = 0.90
; total filament cost = 0.02
; estimated printing time (normal mode) = 4m 32s
; estimated first layer printing time (normal mode) = 4m 32s

; prusaslicer_config = begin
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 1
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = -500x-500,500x-500,500x500,-500x500
; bed_temperature = 60
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.6
; bridge_acceleration = 500
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 30
; brim_separation = 0
; brim_type = no_brim
; brim_width = 10
; color_change_gcode = ;change filament\nM600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 500
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 30
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = G91\nG1 F1800 E-3\nG1 F3000 Z10\nG90\nM106 S0 ; turn off cooling fan\nM104 S0 ; turn off extruder\nM140 S0 ; turn off bed\nM84 ; disable motors
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 100%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FF0000
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.4
; fan_always_on = 1
; fan_below_layer_time = 10
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 23
; filament_density = 1.25
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = pla+
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 0%
; fill_pattern = rectilinear
; first_layer_acceleration = 500
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0
; first_layer_height = 0.2
; first_layer_speed = 40
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.2
; fuzzy_skin_thickness = 0.4
; gap_fill_enabled = 1
; gap_fill_speed = 30
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 500
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 30
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,150
; machine_max_feedrate_x = 500,100
; machine_max_feedrate_y = 500,100
; machine_max_feedrate_z = 12,100
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.32
; max_print_height = 400
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 30
; min_feature_size = 0.1
; min_layer_height = 0.08
; min_print_speed = 10
; min_skirt_length = 10
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 500
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 30
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.2
; printer_model = 
; printer_notes = 
; printer_settings_id = blender prep
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.3
; raft_expansion = 5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 0
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 0
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 5
; skirt_height = 1
; skirts = 5
; slice_closing_radius = 0
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 100%
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 100%
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\nM900 K0.06 ;lin_adv fact\n"
; start_gcode = M900 K0.13 ;lin_adv fact\nG28 ;Home\nG29 ;auto level\n\nG1 Z15.0 F6000 ;Move the platform down 15mm\nG92 E0\nG1 F200 E5\nG92 E0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 0
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear-grid
; support_material_spacing = 8
; support_material_speed = 30
; support_material_style = organic
; support_material_synchronize_layers = 0
; support_material_threshold = 80
; support_material_with_sheath = 0
; support_material_xy_spacing = 0.2
; support_tree_angle = 45
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 100%
; top_solid_layers = 4
; top_solid_min_thickness = 0.6
; travel_acceleration = 0
; travel_speed = 30
; travel_speed_z = 0
; use_firmware_retraction = 1
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
